# version: "3.9"

# services:
#   backend:
#     image: codecrafterx/backend-ci:latest
#     expose:
#       - "3000"

#   nginx:
#     image: nginx:alpine
#     container_name: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./frontend-ci/dist:/usr/share/nginx/html   # <-- use correct folder name
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - backend


version: "3.9"

services:
  backend:
    image: codecrafterx/backend-ci:latest
    container_name: backend
    expose:
      - "3000"
    restart: always

  frontend:
    image: codecrafterx/frontend-ci:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
